routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('student.auth.login');
});
Route::get('image/{folder}/{path}/{size?}', 'Controller@photo');



Route::group(['middleware'  => 'auth:student,teacher'], function () {




    Route::group(['prefix'  => 'group/{id}' ,'as' => 'groups.' ,  'namespace' => 'Front'], function () {
        Route::get('/' , ['as' => 'show' , 'uses' => 'GroupController@show']);


        Route::group(['prefix'  => 'posts' , 'as' => 'posts.'], function () {

            Route::group(['prefix'  => 'add' ], function () {
                Route::get('/' , ['as' => 'add' , 'uses' => 'GroupPostController@create']);
                Route::post('/', ['as' => 'add' , 'uses' => 'GroupPostController@store']);
            });

            Route::get('{post_id}' , ['as' => 'show' , 'uses' => 'GroupPostController@show'] );
            Route::delete('{post_id}' , ['as' => 'destroy' , 'uses' => 'GroupPostController@destroy'] );


            Route::group(['prefix'  => 'replies' , 'as' => 'replies.' ], function () {
                Route::post('/store', ['as' => 'store' , 'uses' => 'GroupPostController@storeReplay']);
            });

        });

    });




    Route::group(['prefix'  => 'books' , 'as' => 'books.', 'namespace' => 'Front'], function () {
        Route::get('/' , ['as' => 'index' , 'uses' => 'BookRequestController@index']);


        Route::group(['prefix'  => 'create' ], function () {
            Route::get('/' , ['as' => 'create' , 'uses' => 'BookRequestController@create']);
            Route::post('/', ['as' => 'store' , 'uses' => 'BookRequestController@store']);
        });

    });






});

app/GroupPosts.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GroupPosts extends Model
{
    protected $fillable = [
      'group_id','content','owner_id','owner_type',
    ];

    public function photos()
    {
        return $this->hasMany(Photo::class , 'group_post_id' , 'id');
    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class , 'group_post_id' , 'id');
    }

}

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Teacher extends Authenticatable
{
    protected $fillable = [
        'name' , 'email' , 'mobile' , 'password' , 'avatar'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function scopeFilter($q , $search)
    {
        return $q->where('name' , 'like' , '%'.$search.'%')
            ->orWhere('email' , 'like' , '%'.$search.'%')
            ->orWhere('mobile' , 'like' , '%'.$search.'%');
    }


    public function groups()
    {
        return $this->hasMany(Group::class)->where('is_accepted' , 1);
    }
}

app/Http/Controllers/Front/GroupPostController.php
<?php

namespace App\Http\Controllers\Front;

use App\Comment;
use App\Group;
use App\GroupPosts;
use App\Photo;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class GroupPostController extends Controller
{

    protected $path = 'posts';
    public function create($id)
    {
        $data['group'] = Group::findOrFail($id);

        return view('front.teacher.groupPosts.create', $data);
    }

    public function store($id , Request $request)
    {
        $group = Group::findOrFail($id);
        $data = $request->all();

        $data['owner_type'] = get_class($request->user());
        $data['owner_id'] = $request->user()->id ;
        $data['group_id'] = $group->id ;

        $validator = Validator::make($data , [
            'content'  => 'required|string',
            'image'    => 'image'
        ]);

        if ($validator->fails()){
            return redirect()->back()->withErrors($validator);
        }

        $post = GroupPosts::create($data);

        if ($file = $request->file('image')){
            $dataImage['path'] = $file->store($this->path);
            $dataImage['group_post_id'] = $post->id;

            Photo::create($dataImage);
        }

        return back()->with('success' , 'تمت العملية بنجاح');

    }

    public function show($id , $post_id)
    {
        $data['post'] = GroupPosts::findOrFail($post_id);
        return view('front.teacher.groupPosts.show' ,$data);
    }

    public function storeReplay(Request $request)
    {
        $data = $request->all();

        $validator = Validator::make($data , [
            'replay'  => 'required|string',
        ]);

        if ($validator->fails()){
            return redirect()->back()->withErrors($validator);
        }

        $data['group_post_id'] = $request->post_id;
        $data['content'] = $request->replay;
        $data['owner_type'] = get_class($request->user());
        $data['owner_id'] = $request->user()->id ;
        Comment::create($data);

        return back()->with('success' , 'تمت العملية بنجاح');
    }

//
//    public function destroy($id , $file_id)
//    {
//
//        try {
//            GroupFiles::destroy($file_id);
//
//            return response()->json([
//                'status' => 200,
//                'msg' => 'لقد تمت عملية الحذف بنجاح'
//            ], 200);
//
//        } catch (\Exception $exception) {
//            return response()->json([
//                'status' => 500,
//                'msg' => 'لقد حدث خطأ ما'
//            ], 500);
//        }
//    }
}

app/Http/Controllers/Front/Teacher/GroupFileController.php
<?php

namespace App\Http\Controllers\Front\Teacher;

use App\Group;
use App\GroupFiles;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;

class GroupFileController extends Controller
{

    protected $path = 'files';

    public function create($id)
    {
        $data['group'] = Group::findOrFail($id);

        return view('front.teacher.groupFiles.create', $data);
    }

    public function store($id , Request $request)
    {
        $group = Group::findOrFail($id);
        $data = $request->all();

        $validator = Validator::make($data , [
            'file'  => 'required|file'
        ]);

        if ($validator->fails()){
            return redirect()->back()->withErrors($validator);
        }


        if ($file = $request->file('file')){
            $data['path'] = $file->store($this->path);
            $path = storage_path("app/" .$data['path']);

            $data['mime'] = File::mimeType($path);
            $data['size'] = File::size($path);
            $data['name'] = $file->getClientOriginalName();
            $data['group_id'] = $group->id;
            GroupFiles::create($data);
            return back()->with('success' , 'تمت العملية بنجاح');
        }

        return back()->with('error' , 'لقد حدث خطأ ما');

    }

    public function destroy($id , $file_id)
    {

        try {
            GroupFiles::destroy($file_id);

            return response()->json([
                'status' => 200,
                'msg' => 'لقد تمت عملية الحذف بنجاح'
            ], 200);

        } catch (\Exception $exception) {
            return response()->json([
                'status' => 500,
                'msg' => 'لقد حدث خطأ ما'
            ], 500);
        }
    }

    public function download($id , $file_id)
    {
        $file = GroupFiles::findOrFail($file_id);


        $path = storage_path("app/".$file->path);

        return response()->download($path);

    }
}

app/Http/Controllers/Front/Teacher/GroupStudentController.php
<?php

namespace App\Http\Controllers\Front\Teacher;

use App\Admin;
use App\Group;
use App\GroupStudent;
use App\Student;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GroupStudentController extends Controller
{
    public function datatable($id)
    {
        $group = Group::findOrFail($id);
        $items = $group->students();

        return getDataTable($items);
    }

    public function create($id)
    {
        $data['group'] = Group::findOrFail($id);
        $data['students'] = Student::all();
        return view('front.teacher.groupStudents.create', $data);
    }

    public function store($id , Request $request)
    {

        $group = Group::findOrFail($id);


        if (isset($request->students) && count($request->students) > 0 ){
            foreach ($request->students as $item) {
                $std = Student::find(['id' => $item]);
                if (!isset($std)) {
                    return redirect()->back()->with('error' , 'لقد حدث خطأ ما');
                }else{
                    if (!$group->students()->where('id' , $item)->first()){
                        $group->students()->attach($std);
                    }
                }

            }
        }

        return back()->with('success' , 'تمت العملية بنجاح');
    }

    public function destroy($id , $std_id)
    {
        try {
            GroupStudent::where('group_id' , $id)
                        ->where('student_id' , $std_id)
                        ->delete();

            return response()->json([
                'status' => 200,
                'msg' => 'لقد تمت عملية الحذف بنجاح'
            ], 200);

        } catch (\Exception $exception) {
            return response()->json([
                'status' => 500,
                'msg' => 'لقد حدث خطأ ما'
            ], 500);
        }
    }
}

app/Http/Controllers/Front/Teacher/HomeController.php
<?php

namespace App\Http\Controllers\Front\Teacher;

use App\Catagory;
use App\Course;
use App\Lecture;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{

    public function index()
    {
        return view('front.main.index');
    }
}

app/Http/Controllers/Panel/TeacherController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Constants\StatusCodes;
use App\Http\Requests\TeacherRequest;
use App\Teacher;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;

class TeacherController extends Controller
{
    protected $storagePath = 'teachers';

    public function index()
    {
        return view('panel.teachers.index');
    }


    public function create()
    {
        return view('panel.teachers.create');
    }


    public function store(TeacherRequest $request)
    {
        $data = $request->all();
        $data['password'] = Hash::make($data['password']);

        if ($file = $request->file('avatar')){
            $data['avatar'] = $file->store($this->storagePath);
        }


        Teacher::create($data);

        return response()->json([
            'msg' => 'تمت عملية الإضافة بنجاح'
        ], StatusCodes::OK);

    }

    public function edit($id)
    {
        $data['teacher'] = Teacher::findOrFail($id);
        return view('panel.teachers.edit', $data);
    }


    public function update(TeacherRequest $request, $id)
    {
        $teacher = Teacher::findOrFail($id);
        $data = $request->all();

        if (!$request->filled('password')) {
            $data['password'] = $teacher->password;
        }else{
            $data['password'] = Hash::make($data['password']);
        }

        if ($file = $request->file('avatar')){
            $data['avatar'] = $file->store($this->storagePath);
            Storage::delete($teacher->avatar);
        }

        $teacher->update($data);

        return response()->json([
            'msg' => 'تمت عملية التعديل بنجاح'
        ], 200);
    }


    public function destroy($id)
    {
        try {
            $admin = Teacher::destroy($id);

            return response()->json([
                'status' => 200,
                'msg' => 'لقد تمت عملية الحذف بنجاح'
            ], 200);

        } catch (\Exception $exception) {
            return response()->json([
                'status' => 500,
                'msg' => 'لقد حدث خطأ ما'
            ], 500);
        }
    }

    public function datatable()
    {
        $pagination = Input::get('pagination');
        $query = Input::get('query');

        $search = $query['generalSearch'];


        $sort = Input::get('sort');


        if ($pagination['perpage'] == -1 || $pagination['perpage'] == null) {
            $pagination['perpage'] = 10;
        }
        $items = Teacher::query();


        if ($search != null) {
            $items->filter($search);
        }

        if ($sort && count($sort)) {
            $items->orderBy($sort['field'], $sort['sort']);
        } else {
            $items->orderByDesc('created_at');
        }

        $itemsCount = $items->count();
        $items = $items->take($pagination['perpage'])->skip($pagination['perpage'] * ($pagination['page'] - 1))->get();
        $pagination['total'] = $itemsCount;
        $pagination['pages'] = ceil($itemsCount / $pagination['perpage']);

        $data['meta'] = $pagination;
        $data['data'] = $items;
        return $data;
    }

}

resources/views/front/teacher/groupPosts/create.blade.php
@extends('front.layout.master' , ['title' => 'نشر خبر'])

@push('css')
    <link href="{{ asset('panelAssets/js/summernote/dist/summernote.css') }}" rel="stylesheet" type="text/css"/>
@endpush

@section('subheade')
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container ">
            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">الرئيسية </h3>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="{{ route('groups.show' , $group->id ) }}" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('groups.show' , $group->id ) }}" class="kt-subheader__breadcrumbs-link"> {{ $group->name }} </a>
                </div>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="" class="kt-subheader__breadcrumbs-link"> نشر خبر </a>
                </div>
            </div>

        </div>
    </div>
@endsection


@section('content')

    <form class="kt-form kt-form--fit kt-form--label-right" action="{{ route('groups.posts.add' , $group->id) }}"
          method="post" enctype="multipart/form-data">

        <div class="row">
            <div class="col-md-9">
                <div class="kt-portlet">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">
                                نشر خبر
                            </h3>
                        </div>
                    </div>

                    <!--begin::Form-->

                    @csrf
                    <div class="kt-portlet__body">
                        @if ($errors->any())
                            <div class="alert alert-danger">{{ $errors->first() }}</div>
                        @endif
                        @if ( session('error') )
                            <div class="alert alert-danger">{{ session('error') }}</div>
                        @endif
                        @if (session('success'))
                            <div class="alert alert-success">{{ session('success') }}</div>
                        @endif

                        <div class="form-group">
                            <label>محتوى الخبر</label>
                            <div></div>
                            <textarea class="summernote form-control" style="display:none!important;"
                                      id="kt_summernote_1"
                                      name="content" placeholder="محتوى الخبر">{{ old('content') }}</textarea>
                        </div>


                    </div>


                    <!--end::Portlet-->


                </div>
            </div>

            <div class="col-lg-3">
                <div class="kt-portlet">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label" style="width: 100%;">
                            <button type="submit" style="width: 100%;" id="save" class="btn btn-brand">إضافة</button>
                        </div>
                    </div>
                </div>

                <div class="kt-portlet">
                    <div class="kt-portlet__body ">


                        <div class="form-group">
                            <label>صورة الخبر</label>
                            <div></div>
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="imgload" name="image">
                                <label class="custom-file-label" style="text-align: right!important;"  for="imgload">Choose file</label>
                            </div>
                        </div>

                        <div class="img-responsive">
                            <div class="imageEditProfile">
                                <img src="" alt="" id="imgshow" style="max-width: 100%">
                            </div>
                        </div>

                    </div>

                </div>

            </div>
        </div>
    </form>

@endsection


@push('js')

    <script src="{{ asset('panelAssets/js/summernote/dist/summernote.js') }}" type="text/javascript"></script>
    <script src="{{ asset('panelAssets/js/summernote.min.js') }}" type="text/javascript"></script>

    <script !src="">
        $("#imgload").change(function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#imgshow').attr('src', e.target.result);
                }
                reader.readAsDataURL(this.files[0]);
            }
        });

    </script>
@endpush

resources/views/front/teacher/groupPosts/show.blade.php
@extends('front.layout.master', ['title' => 'عرض الخبر' ])



@section('subheade')
    <div class="kt-subheader   kt-grid__item" id="kt_subheader">
        <div class="kt-container ">
            <div class="kt-subheader__main">
                <h3 class="kt-subheader__title">الرئيسية </h3>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="{{ route('groups.show' , $post->group->id) }}" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="{{ route('groups.show' , $post->group->id) }}" class="kt-subheader__breadcrumbs-link"> {{ $post->group->name }} </a>
                </div>
                <span class="kt-subheader__separator kt-hidden"></span>
                <div class="kt-subheader__breadcrumbs">
                    <a href="#" class="kt-subheader__breadcrumbs-home"><i class="flaticon2-shelter"></i></a>
                    <span class="kt-subheader__breadcrumbs-separator"></span>
                    <a href="" class="kt-subheader__breadcrumbs-link"> الأخبار </a>
                </div>
            </div>

        </div>
    </div>
@endsection


@section('content')

    <div class="kt-portlet kt-portlet--mobile">
        @if ($post->photos->count())
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label p-3 mx-auto">
                    <img src="{{ url('image/' . $post->photos[0]->path . '/300x300' ) }}" alt="">
                </div>
            </div>
        @endif
        <div class="kt-portlet__body">
            {!! $post->content !!}
        </div>
    </div>

    <div class="kt-portlet kt-portlet--mobile">
        <div class="kt-portlet__body">
            @if ($errors->any())
                <div class="alert alert-danger">{{ $errors->first() }}</div>
            @endif
            @if ( session('error') )
                <div class="alert alert-danger">{{ session('error') }}</div>
            @endif
            @if (session('success'))
                <div class="alert alert-success">{{ session('success') }}</div>
            @endif

            <form action="{{ route('groups.posts.replies.store' , $post->group_id) }}" method="post">

                @csrf
                <input type="hidden" name="post_id" value="{{ $post->id }}">
                <div class="form-group">
                    <label>الرد على الخبر</label>
                    <textarea class="form-control mt-2" rows="5" name="replay"
                              placeholder="الرد على الخبر">{{ old('replay') }}</textarea>
                </div>
                <div class="kt-portlet__foot">
                    <button type="submit" class="btn btn-brand btn-elevate btn-icon-sm">
                        ارسال رد
                    </button>
                </div>

            </form>

        </div>
    </div>

    @foreach($post->comments as $comment)

        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head p-3">
                <div class="col-md-6">{{ $comment->owner_name }}</div>
                <div class="col-md-6 text-right">{{ $comment->created_at->format('Y-m-d g:i A') }}</div>
            </div>

            <div class="kt-portlet__body">
                {!! $comment->content !!}
            </div>
        </div>

    @endforeach

@endsection
@push('js')



@endpush